disabled_rules:
  - colon
  - cyclomatic_complexity
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - line_length
  - file_length
  - nesting
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
  - identifier_name
  - shorthand_operator
  - large_tuple
  - redundant_string_enum_value
  - multiple_closures_with_trailing_closure
  - opening_brace
  
opt_in_rules:
  - explicit_init
  - overridden_super_call

excluded:
